# Generated by Django 3.2.4 on 2021-07-07 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('price', models.FloatField()),
                ('description', models.TextField(max_length=5000)),
            ],
        ),
    ]
