# Generated by Django 3.2.4 on 2021-07-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_delete_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stripe_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=500)),
                ('payment_method', models.CharField(max_length=100)),
                ('paymment_status', models.CharField(max_length=500)),
                ('transaction_id', models.CharField(max_length=500)),
            ],
        ),
    ]
