# Generated by Django 3.2.4 on 2021-07-13 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_stripe_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripe_data',
            name='payment_method',
        ),
    ]
