# Generated by Django 3.2.4 on 2021-07-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_stripe_data_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripe_data',
            name='price',
            field=models.IntegerField(default=10.0),
            preserve_default=False,
        ),
    ]
