# Generated by Django 3.2.4 on 2021-07-13 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210713_1105'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stripe_Data',
        ),
    ]
