# Generated by Django 3.2.4 on 2021-07-13 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0007_delete_stripe_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stripe_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_email', models.EmailField(max_length=500)),
                ('model_paymment_status', models.CharField(max_length=500)),
                ('model_transaction_id', models.CharField(max_length=500)),
                ('model_price', models.IntegerField()),
            ],
        ),
    ]
