# Generated by Django 3.2.4 on 2021-07-13 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_stripe_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripe_data',
            name='model_price',
            field=models.FloatField(),
        ),
    ]
