# Generated by Django 3.2.4 on 2021-07-13 11:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_stripe_data_model_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripe_data',
            name='model_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
