# Generated by Django 3.2.4 on 2021-07-13 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_stripe_data_model_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stripe_Data',
        ),
    ]
